name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.16.2

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          apt-get update
          apt-get -y install curl
          curl https://github.com/joinself/self-omemo/releases/download/0.4.0/self-omemo_0.4.0_amd64.deb
          apt-get -y install ./self-omemo_0.4.0_amd64.deb

      - name: Test
        run: go test -v ./...
