name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-compliance:
    uses: joinself/github-workflows-public/.github/workflows/license-compliance.yml@main
    secrets: inherit
  test:
    needs: license-compliance
    uses: ./.github/workflows/test.yml
    secrets: inherit
